---

- name: Create working directory
  file:
    path: /usr/src
    state: directory

- name: Download chruby
  get_url:
    url: https://github.com/postmodern/chruby/archive/v{{ chruby_version }}.tar.gz
    dest: /usr/src/chruby-{{ chruby_version }}.tar.gz
  when:
    ansible_local is not defined or
    ansible_local.chruby is not defined or
    ansible_local.chruby.version != chruby_version
  register: chruby_downloaded

- name: Extract chruby
  shell: tar -C /usr/src -xzvf /usr/src/chruby-{{ chruby_version }}.tar.gz
  when: chruby_downloaded | changed
  register: chruby_extracted

- name: Install chruby
  sudo: true
  shell: cd /usr/src/chruby-{{ chruby_version }}/ && make install
  when: chruby_extracted | changed
  register: chruby_installed

- name: Clean up chruby sources
  shell: rm -rf /usr/src/chruby-*
  when: chruby_downloaded | changed

- name: Attach chruby into shell
  sudo: true
  template: src=chruby.sh dest=/etc/profile.d/chruby.sh

#
# Setup chruby facts.d
#
- name: Capture installed chruby version
  shell: >
    executable=/bin/bash source /etc/profile;
    chruby --version | awk '{ print $2 }'
  ignore_errors: yes
  register: installed_chruby_version

- name: Create ansible facts directory
  sudo: true
  file: state=directory recurse=yes path=/etc/ansible/facts.d

- name: Set chruby facts
  sudo: true
  template: src=chruby.fact dest=/etc/ansible/facts.d/chruby.fact
